# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 00:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sanpham.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id_danhmuc', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hinhanh', models.ImageField(blank=True, null=True, upload_to=sanpham.models.upload_hinhanh_danhmuc)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('danhmuc_cha', models.ForeignKey(blank=True, db_column='id_danhmuc_cha', null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.DanhMuc')),
            ],
            options={
                'db_table': 'danhmuc',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id_sanpham', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=255)),
                ('hinhanh', models.ImageField(blank=True, null=True, upload_to=sanpham.models.upload_hinhanh_sanpham)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('mota', models.TextField(blank=True, null=True)),
                ('dongia', models.PositiveIntegerField(default=0)),
                ('donvi', models.CharField(max_length=120)),
                ('chatlieu', models.CharField(max_length=120)),
                ('trongluong', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('chieudai', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('chieurong', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('chieucao', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('soluong', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vitri', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField(default=True)),
                ('noibat', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('danhmuc', models.ForeignKey(blank=True, db_column='id_danhmuc', null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.DanhMuc')),
            ],
            options={
                'db_table': 'sanpham',
            },
        ),
    ]
