# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 00:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id_giohang', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('sdt', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ', regex='^\\d{10,11}$')])),
                ('diachi', models.CharField(max_length=255)),
                ('tinh_thanh', models.CharField(max_length=50)),
                ('quan_huyen', models.CharField(max_length=50)),
                ('xa_phuong', models.CharField(max_length=50)),
                ('phigiaohang', models.PositiveIntegerField(default=0)),
                ('giamgia', models.PositiveIntegerField(default=0)),
                ('tong_thanhtien', models.PositiveIntegerField(default=0)),
                ('tong_cong', models.PositiveIntegerField(default=0)),
                ('loai_thanhtoan', models.CharField(blank=True, choices=[('cod', 'COD'), ('credit', 'Thẻ tín Dụng')], max_length=6, null=True)),
                ('so_the', models.CharField(blank=True, max_length=19, null=True)),
                ('hoten_the', models.CharField(blank=True, max_length=50, null=True)),
                ('ngayhethan', models.CharField(blank=True, max_length=9, null=True)),
                ('ccv', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(choices=[('created', 'Đã tạo giỏ hàng'), ('paid', 'Đã thanh toán'), ('shipping', 'Đang giao hàng'), ('shipped', 'Đã giao hàng')], default='created', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('capnhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'giohang',
            },
        ),
        migrations.CreateModel(
            name='GioHangSanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('thanhtien', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('giohang', models.ForeignKey(db_column='id_giohang', on_delete=django.db.models.deletion.CASCADE, to='giohang.GioHang')),
                ('sanpham', models.ForeignKey(db_column='id_sanpham', on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham')),
            ],
            options={
                'db_table': 'giohang_sanpham',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='giohang',
            name='sanpham',
            field=models.ManyToManyField(through='giohang.GioHangSanPham', to='sanpham.SanPham'),
        ),
        migrations.AddField(
            model_name='giohang',
            name='taikhoan',
            field=models.ForeignKey(blank=True, db_column='id_taikhoan', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='giohangsanpham',
            unique_together=set([('giohang', 'sanpham')]),
        ),
    ]
