# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giohang',
            name='exp_month',
        ),
        migrations.RemoveField(
            model_name='giohang',
            name='exp_year',
        ),
        migrations.AddField(
            model_name='giohang',
            name='ngayhethan',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
