# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giohang',
            options={'ordering': ['-timestamp', '-capnhat']},
        ),
    ]
