# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0002_auto_20180506_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='giohang',
            name='ngaydat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
