# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giohang', '0003_auto_20180501_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='so_the',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
