# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-28 08:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhVien',
            fields=[
                ('id_thanhvien', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ngaysinh', models.DateField(blank=True, null=True)),
                ('gioitinh', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('undefined', 'Chưa xác định')], default='undefined', max_length=9)),
                ('sdt', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ', regex='^\\d{10,11}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taikhoan',
            },
        ),
        migrations.CreateModel(
            name='BoPhan',
            fields=[
                ('id_bophan', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ten_bophan', models.CharField(blank=True, max_length=255, null=True)),
                ('mota', models.TextField()),
            ],
            options={
                'db_table': 'bophan',
            },
        ),
        migrations.CreateModel(
            name='Khach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'khach',
            },
        ),
        migrations.CreateModel(
            name='NhanVienBoPhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bophan', models.ForeignKey(db_column='id_bophan', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='taikhoan.BoPhan', verbose_name='bophan')),
                ('thanhvien', models.ForeignKey(db_column='id_thanhvien', db_index=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='thanhvien')),
            ],
            options={
                'db_table': 'nhanvien_bophan',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nhanvienbophan',
            unique_together=set([('thanhvien', 'bophan')]),
        ),
    ]
